In [1]:
import pandas as pd

In [2]:
test=pd.read_csv(r"C:\Users\ARIO\Documents\for IK saber\aps_failure_test_set.csv",na_values='na')
train = pd.read_csv(r"C:\Users\ARIO\Documents\for IK saber\aps_failure_training_set.csv",na_values='na')

In [3]:
print(train.shape)
train.head()

(60000, 171)

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,76698,NaN,2.130706e+09,280.0,0.0,0.0,0.0,0.0,0.0,...,1240520.0,493384.0,721044.0,469792.0,339156.0,157956.0,73224.0,0.0,0.0,0.0
1,neg,33058,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,...,421400.0,178064.0,293306.0,245416.0,133654.0,81140.0,97576.0,1500.0,0.0,0.0
2,neg,41040,NaN,2.280000e+02,100.0,0.0,0.0,0.0,0.0,0.0,...,277378.0,159812.0,423992.0,409564.0,320746.0,158022.0,95128.0,514.0,0.0,0.0
3,neg,12,0.0,7.000000e+01,66.0,0.0,10.0,0.0,0.0,0.0,...,240.0,46.0,58.0,44.0,10.0,0.0,0.0,0.0,4.0,32.0
4,neg,60874,NaN,1.368000e+03,458.0,0.0,0.0,0.0,0.0,0.0,...,622012.0,229790.0,405298.0,347188.0,286954.0,311560.0,433954.0,1218.0,0.0,0.0

In [4]:
null_count = train.isnull().sum()
null_count

class         0
aa_000        0
ab_000    46329
ac_000     3335
ad_000    14861
          ...
ee_007      671
ee_008      671
ee_009      671
ef_000     2724
eg_000     2723
Length: 171, dtype: int64

In [5]:
missing_percent = null_count / len(train) *100
missing_percent

class      0.000000
aa_000     0.000000
ab_000    77.215000
ac_000     5.558333
ad_000    24.768333
            ...
ee_007     1.118333
ee_008     1.118333
ee_009     1.118333
ef_000     4.540000
eg_000     4.538333
Length: 171, dtype: float64

In [6]:
cols_to_drop = missing_percent[missing_percent > 50].index
cols_to_drop

Index(['ab_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000', 'bq_000', 'br_000',
       'cr_000'],
      dtype='object')

In [7]:
train_clean = train.drop(columns=cols_to_drop)
train_clean

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,76698,2.130706e+09,280.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1240520.0,493384.0,721044.0,469792.0,339156.0,157956.0,73224.0,0.0,0.0,0.0
1,neg,33058,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,421400.0,178064.0,293306.0,245416.0,133654.0,81140.0,97576.0,1500.0,0.0,0.0
2,neg,41040,2.280000e+02,100.0,0.0,0.0,0.0,0.0,0.0,0.0,...,277378.0,159812.0,423992.0,409564.0,320746.0,158022.0,95128.0,514.0,0.0,0.0
3,neg,12,7.000000e+01,66.0,0.0,10.0,0.0,0.0,0.0,318.0,...,240.0,46.0,58.0,44.0,10.0,0.0,0.0,0.0,4.0,32.0
4,neg,60874,1.368000e+03,458.0,0.0,0.0,0.0,0.0,0.0,0.0,...,622012.0,229790.0,405298.0,347188.0,286954.0,311560.0,433954.0,1218.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,neg,153002,6.640000e+02,186.0,0.0,0.0,0.0,0.0,0.0,2564.0,...,998500.0,566884.0,1290398.0,1218244.0,1019768.0,717762.0,898642.0,28588.0,0.0,0.0
59996,neg,2286,2.130707e+09,224.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10578.0,6760.0,21126.0,68424.0,136.0,0.0,0.0,0.0,0.0,0.0
59997,neg,112,2.130706e+09,18.0,0.0,0.0,0.0,0.0,0.0,0.0,...,792.0,386.0,452.0,144.0,146.0,2622.0,0.0,0.0,0.0,0.0
59998,neg,80292,2.130706e+09,494.0,0.0,0.0,0.0,0.0,0.0,0.0,...,699352.0,222654.0,347378.0,225724.0,194440.0,165070.0,802280.0,388422.0,0.0,0.0
59999,neg,40222,6.980000e+02,628.0,0.0,0.0,0.0,0.0,0.0,0.0,...,440066.0,183200.0,344546.0,254068.0,225148.0,158304.0,170384.0,158.0,0.0,0.0

In [8]:
train['ae_000'].value_counts()

ae_000
0.0      55543
2.0        601
4.0        105
6.0         63
8.0         60
         ...
946.0        1
626.0        1
606.0        1
362.0        1
700.0        1
Name: count, Length: 333, dtype: int64

In [9]:
median = train_clean.median(numeric_only=True)

In [10]:
train_filled = train_clean.fillna(median)
train_filled

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,76698,2.130706e+09,280.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1240520.0,493384.0,721044.0,469792.0,339156.0,157956.0,73224.0,0.0,0.0,0.0
1,neg,33058,0.000000e+00,126.0,0.0,0.0,0.0,0.0,0.0,0.0,...,421400.0,178064.0,293306.0,245416.0,133654.0,81140.0,97576.0,1500.0,0.0,0.0
2,neg,41040,2.280000e+02,100.0,0.0,0.0,0.0,0.0,0.0,0.0,...,277378.0,159812.0,423992.0,409564.0,320746.0,158022.0,95128.0,514.0,0.0,0.0
3,neg,12,7.000000e+01,66.0,0.0,10.0,0.0,0.0,0.0,318.0,...,240.0,46.0,58.0,44.0,10.0,0.0,0.0,0.0,4.0,32.0
4,neg,60874,1.368000e+03,458.0,0.0,0.0,0.0,0.0,0.0,0.0,...,622012.0,229790.0,405298.0,347188.0,286954.0,311560.0,433954.0,1218.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,neg,153002,6.640000e+02,186.0,0.0,0.0,0.0,0.0,0.0,2564.0,...,998500.0,566884.0,1290398.0,1218244.0,1019768.0,717762.0,898642.0,28588.0,0.0,0.0
59996,neg,2286,2.130707e+09,224.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10578.0,6760.0,21126.0,68424.0,136.0,0.0,0.0,0.0,0.0,0.0
59997,neg,112,2.130706e+09,18.0,0.0,0.0,0.0,0.0,0.0,0.0,...,792.0,386.0,452.0,144.0,146.0,2622.0,0.0,0.0,0.0,0.0
59998,neg,80292,2.130706e+09,494.0,0.0,0.0,0.0,0.0,0.0,0.0,...,699352.0,222654.0,347378.0,225724.0,194440.0,165070.0,802280.0,388422.0,0.0,0.0
59999,neg,40222,6.980000e+02,628.0,0.0,0.0,0.0,0.0,0.0,0.0,...,440066.0,183200.0,344546.0,254068.0,225148.0,158304.0,170384.0,158.0,0.0,0.0

In [11]:
from sklearn.feature_selection import VarianceThreshold
x = train_filled.drop(columns=['class'])
y = train_filled['class']

In [12]:
selector = VarianceThreshold(threshold=0.01)
x_reduce = selector.fit_transform(x)
x_reduce

array([[7.66980000e+04, 2.13070644e+09, 2.80000000e+02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.30580000e+04, 0.00000000e+00, 1.26000000e+02, ...,
        1.50000000e+03, 0.00000000e+00, 0.00000000e+00],
       [4.10400000e+04, 2.28000000e+02, 1.00000000e+02, ...,
        5.14000000e+02, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.12000000e+02, 2.13070643e+09, 1.80000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.02920000e+04, 2.13070643e+09, 4.94000000e+02, ...,
        3.88422000e+05, 0.00000000e+00, 0.00000000e+00],
       [4.02220000e+04, 6.98000000e+02, 6.28000000e+02, ...,
        1.58000000e+02, 0.00000000e+00, 0.00000000e+00]])

In [13]:
x_reduce.shape

(60000, 160)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x_reduce)
x_scaled

array([[ 1.19381409e-01,  2.31022415e+00, -4.08499000e-03, ...,
        -1.75698603e-01, -2.02567552e-02, -2.35397175e-02],
       [-1.80696612e-01, -4.32858945e-01, -4.08938435e-03, ...,
        -1.43927082e-01, -2.02567552e-02, -2.35397175e-02],
       [-1.25810664e-01, -4.32858652e-01, -4.09012626e-03, ...,
        -1.64811562e-01, -2.02567552e-02, -2.35397175e-02],
       ...,
       [-4.07240391e-01,  2.31022414e+00, -4.09246611e-03, ...,
        -1.75698603e-01, -2.02567552e-02, -2.35397175e-02],
       [ 1.44094526e-01,  2.31022414e+00, -4.07888355e-03, ...,
         8.05147339e+00, -2.02567552e-02, -2.35397175e-02],
       [-1.31435408e-01, -4.32858047e-01, -4.07505989e-03, ...,
        -1.72352003e-01, -2.02567552e-02, -2.35397175e-02]])

In [15]:
print(test.shape)
test.head()

(16000, 171)

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,60,0.0,20.0,12.0,0.0,0.0,0.0,0.0,0.0,...,1098.0,138.0,412.0,654.0,78.0,88.0,0.0,0.0,0.0,0.0
1,neg,82,0.0,68.0,40.0,0.0,0.0,0.0,0.0,0.0,...,1068.0,276.0,1620.0,116.0,86.0,462.0,0.0,0.0,0.0,0.0
2,neg,66002,2.0,212.0,112.0,0.0,0.0,0.0,0.0,0.0,...,495076.0,380368.0,440134.0,269556.0,1315022.0,153680.0,516.0,0.0,0.0,0.0
3,neg,59816,NaN,1010.0,936.0,0.0,0.0,0.0,0.0,0.0,...,540820.0,243270.0,483302.0,485332.0,431376.0,210074.0,281662.0,3232.0,0.0,0.0
4,neg,1814,NaN,156.0,140.0,0.0,0.0,0.0,0.0,0.0,...,7646.0,4144.0,18466.0,49782.0,3176.0,482.0,76.0,0.0,0.0,0.0

In [16]:
null_count = test.isnull().sum()
null_count

class         0
aa_000        0
ab_000    12363
ac_000      926
ad_000     3981
          ...
ee_007      192
ee_008      192
ee_009      192
ef_000      762
eg_000      762
Length: 171, dtype: int64

In [17]:
missing_percent = null_count / len(test) *100
missing_percent

class      0.00000
aa_000     0.00000
ab_000    77.26875
ac_000     5.78750
ad_000    24.88125
            ...
ee_007     1.20000
ee_008     1.20000
ee_009     1.20000
ef_000     4.76250
eg_000     4.76250
Length: 171, dtype: float64

In [18]:
cols_to_drop = missing_percent[missing_percent > 50].index
cols_to_drop

Index(['ab_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000', 'bq_000', 'br_000',
       'cr_000'],
      dtype='object')

In [19]:
test_clean = test.drop(columns=cols_to_drop)
test_clean

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,60,2.000000e+01,12.0,0.0,0.0,0.0,0.0,0.0,2682.0,...,1098.0,138.0,412.0,654.0,78.0,88.0,0.0,0.0,0.0,0.0
1,neg,82,6.800000e+01,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1068.0,276.0,1620.0,116.0,86.0,462.0,0.0,0.0,0.0,0.0
2,neg,66002,2.120000e+02,112.0,0.0,0.0,0.0,0.0,0.0,199486.0,...,495076.0,380368.0,440134.0,269556.0,1315022.0,153680.0,516.0,0.0,0.0,0.0
3,neg,59816,1.010000e+03,936.0,0.0,0.0,0.0,0.0,0.0,0.0,...,540820.0,243270.0,483302.0,485332.0,431376.0,210074.0,281662.0,3232.0,0.0,0.0
4,neg,1814,1.560000e+02,140.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7646.0,4144.0,18466.0,49782.0,3176.0,482.0,76.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,neg,81852,2.130706e+09,892.0,0.0,0.0,0.0,0.0,0.0,0.0,...,632658.0,273242.0,510354.0,373918.0,349840.0,317840.0,960024.0,25566.0,0.0,0.0
15996,neg,18,5.200000e+01,46.0,8.0,26.0,0.0,0.0,0.0,0.0,...,266.0,44.0,46.0,14.0,2.0,0.0,0.0,0.0,0.0,0.0
15997,neg,79636,1.670000e+03,1518.0,0.0,0.0,0.0,0.0,0.0,0.0,...,806832.0,449962.0,778826.0,581558.0,375498.0,222866.0,358934.0,19548.0,0.0,0.0
15998,neg,110,3.600000e+01,32.0,0.0,0.0,0.0,0.0,0.0,0.0,...,588.0,210.0,180.0,544.0,1004.0,1338.0,74.0,0.0,0.0,0.0
15999,neg,8,6.000000e+00,4.0,2.0,2.0,0.0,0.0,0.0,0.0,...,46.0,10.0,48.0,14.0,42.0,46.0,0.0,0.0,0.0,0.0

In [20]:
median = test_clean.median(numeric_only=True)

In [21]:
test_filled = test_clean.fillna(median)
test_filled

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,60,2.000000e+01,12.0,0.0,0.0,0.0,0.0,0.0,2682.0,...,1098.0,138.0,412.0,654.0,78.0,88.0,0.0,0.0,0.0,0.0
1,neg,82,6.800000e+01,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1068.0,276.0,1620.0,116.0,86.0,462.0,0.0,0.0,0.0,0.0
2,neg,66002,2.120000e+02,112.0,0.0,0.0,0.0,0.0,0.0,199486.0,...,495076.0,380368.0,440134.0,269556.0,1315022.0,153680.0,516.0,0.0,0.0,0.0
3,neg,59816,1.010000e+03,936.0,0.0,0.0,0.0,0.0,0.0,0.0,...,540820.0,243270.0,483302.0,485332.0,431376.0,210074.0,281662.0,3232.0,0.0,0.0
4,neg,1814,1.560000e+02,140.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7646.0,4144.0,18466.0,49782.0,3176.0,482.0,76.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,neg,81852,2.130706e+09,892.0,0.0,0.0,0.0,0.0,0.0,0.0,...,632658.0,273242.0,510354.0,373918.0,349840.0,317840.0,960024.0,25566.0,0.0,0.0
15996,neg,18,5.200000e+01,46.0,8.0,26.0,0.0,0.0,0.0,0.0,...,266.0,44.0,46.0,14.0,2.0,0.0,0.0,0.0,0.0,0.0
15997,neg,79636,1.670000e+03,1518.0,0.0,0.0,0.0,0.0,0.0,0.0,...,806832.0,449962.0,778826.0,581558.0,375498.0,222866.0,358934.0,19548.0,0.0,0.0
15998,neg,110,3.600000e+01,32.0,0.0,0.0,0.0,0.0,0.0,0.0,...,588.0,210.0,180.0,544.0,1004.0,1338.0,74.0,0.0,0.0,0.0
15999,neg,8,6.000000e+00,4.0,2.0,2.0,0.0,0.0,0.0,0.0,...,46.0,10.0,48.0,14.0,42.0,46.0,0.0,0.0,0.0,0.0

In [22]:
from sklearn.feature_selection import VarianceThreshold
x_test = test_filled.drop(columns=['class'])
y_test = test_filled['class']

In [23]:
selector = VarianceThreshold(threshold=0.01)
x_test_reduce = selector.fit_transform(x_test)
x_test_reduce

array([[6.0000e+01, 2.0000e+01, 1.2000e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [8.2000e+01, 6.8000e+01, 4.0000e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [6.6002e+04, 2.1200e+02, 1.1200e+02, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [7.9636e+04, 1.6700e+03, 1.5180e+03, ..., 1.9548e+04, 0.0000e+00,
        0.0000e+00],
       [1.1000e+02, 3.6000e+01, 3.2000e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [8.0000e+00, 6.0000e+00, 4.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [24]:
x_test_reduce.shape

(16000, 160)

In [26]:
from sklearn.preprocessing import StandardScaler
x_test_scaled = scaler.transform(x_test_reduce)
x_test_scaled

array([[-0.13492431, -0.43369329, -0.25940467, ..., -0.15962245,
        -0.0187885 , -0.01651709],
       [-0.13488062, -0.43369323, -0.2386814 , ..., -0.15962245,
        -0.0187885 , -0.01651709],
       [-0.00396208, -0.43369304, -0.18539301, ..., -0.15962245,
        -0.0187885 , -0.01651709],
       ...,
       [ 0.02311534, -0.43369117,  0.85521093, ...,  0.20931062,
        -0.0187885 , -0.01651709],
       [-0.13482501, -0.43369327, -0.24460234, ..., -0.15962245,
        -0.0187885 , -0.01651709],
       [-0.13502758, -0.43369331, -0.2653256 , ..., -0.15962245,
        -0.0187885 , -0.01651709]])

In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(class_weight="balanced", max_iter=1000)
model.fit(x_scaled,y)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [29]:
y_hat = model.predict(x_test_scaled)

In [30]:
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_test, y_hat)
print(cm)
print(classification_report(y_test, y_hat))

[[15289   336]
 [   45   330]]
              precision    recall  f1-score   support

         neg       1.00      0.98      0.99     15625
         pos       0.50      0.88      0.63       375

    accuracy                           0.98     16000
   macro avg       0.75      0.93      0.81     16000
weighted avg       0.99      0.98      0.98     16000